### ISSUE TITLE
Resize columns or masonry grid

### ISSUE THREAD

**Issue by danielmcormond** [reallygoodemails/really-good-emails-frontend#11]
Based on Matthew's feedback ~158px is the smallest width we want images to appear.

**Comment by danielmcormond** [comment]
@whale I applied the column sizing we discussed last week. Take a look at this environment:

https://reallygoodemails.herokuapp.com/

Ultimately we will achieve the 7 / 5 / 4 / 2 column layout.
But is this good enough for the initial launch? (check different viewport sizes and devices)

**Comment by whale** [comment]
@danielmcormond 

* Overall the size feels too small. I think we said 160px is smallest for web views as least. I think that means no less than 20px gutter in-between.
* Can we set a CSS max-height to trim super tall images?

**Comment by danielmcormond** [comment]
@whale you're right, you did say 160px initially. I ended up with that smaller size trying to get two columns to fit on mobile.

I just pushed a revision with a 160px grid using 20px gutter and a max height of 500px. It won't scale to two columns if you resize after it loads. But if you're on mobile portrait when you first visit it will be two columns.

Let me know what you think!

**Comment by danielmcormond** [comment]
> The column changes look good.

https://reallygoodemails.slack.com/archives/development/p1482349847000036
