### ISSUE TITLE
Configure Algolia to include larger sized image URLs in it's index

### ISSUE THREAD

**Issue by danielmcormond** [reallygoodemails/really-good-emails-frontend#4]
Right now the Algolia indices only include `thumbnail_url` which are less than 100px wide.

It would be nice to include larger size(s) of the featured post image so we could use the same homepage layout when displaying search results.

This might even allow us to discontinue using WP REST API altogether and use primarily Algolia results for rendering everything on the site (posts, categories, resources, etc.)

Worst case we could use WP REST API to perform the search.

**Comment by danielmcormond** [comment]
To begin, we'll want to upgrade our ancient Algolia WordPress plugin.
We're currently using `0.5.0` and the [latest version](https://community.algolia.com/wordpress) is up to `1.6.0`

It looks like that may automatically yield the additional image sizes we're looking for:
https://github.com/algolia/algoliasearch-wordpress/blob/master/CHANGELOG.md#060

**Comment by danielmcormond** [comment]
Plugin is now upgraded to the latest version. I also triggered a reindex of all our content. Now I'm seeing the full array of image sizes in the Algolia search results.

**Comment by chriscoyier** [comment]
I'm seeing this issue too, with latest copies of plugin.

I get like...

```
  "images": {
    "thumbnail": {
      "url": "http://localhost:8090/wp-content/uploads/2017/02/flex-nav-150x150.png",
      "width": 150,
      "height": 150
    }
  },
```

Any other tricks here?
