### ISSUE TITLE
Categories view

### ISSUE THREAD

**Issue by whale** [reallygoodemails/really-good-emails-frontend#41]
Make 4 columns.
Add 20px vertical padding between items
Place a specific span around the numbers so we can make them uniquely styled.

**Comment by danielmcormond** [comment]
@whale look right? Close this issue if you like it. Comment if you want changes.

http://good.reallygoodemails.com/categories

![image](https://cloud.githubusercontent.com/assets/77014/22990146/3ed29b0a-f386-11e6-9563-8ba86be39b03.png)

**Comment by whale** [comment]
@danielmcormond is it possible to have it run in columns alphabetically?

a   |   e  |  h
c   |   f   |  i
d   |   g  |  j

**Comment by danielmcormond** [comment]
Voilà! Gonna close this issue, but reopen if necessary.

**Comment by whale** [comment]
@danielmcormond can we just add a:hover {text-decoration: underline;}
