### ISSUE TITLE
Make Logo SVG

### ISSUE THREAD

**Issue by whale** [reallygoodemails/really-good-emails-frontend#49]
https://www.dropbox.com/s/3dlrmhpljx32xw8/rge-logo-svg.svg?dl=0

**Comment by danielmcormond** [comment]
@whale when changes are available to test in the [live environment](http://good.reallygoodemails.com), I'll mark them as _Ready_. If you're happy with the changes, move them to _Done_ to close the issue. The easiest way to do that is from [Waffle](https://waffle.io/reallygoodemails/really-good-emails-frontend) but you can also do it directly using GitHub labels.
