### ISSUE TITLE
Smoother Search

### ISSUE THREAD

**Issue by whale** [reallygoodemails/really-good-emails-frontend#54]
* More similar to unsplash.com
* Also, subtle fade in .01 second if it doesn't hurt performance.

**Comment by danielmcormond** [comment]
@whale I put a half-second delay on the search input field. We can tweak that if you want faster or slower reaction to user input.

The best way to see the fade-in is to enable throttling using the _Network_ tab in Chrome DevTools. Use one of the 3G speeds and you'll be able to see the images fade in as they load. Make sure the _Disable cache_ checkbox is enabled too.

**Comment by whale** [comment]
Nice!
